### ISSUE TITLE
Create a sequence diagram

### ISSUE THREAD

**Issue by TakumiHiraide** [ani-hovhannisyan/kanji-visualization#30]

**Comment by TakumiHiraide** [comment]
I created a sequence diagram. I think the teacher said that we need to separate the sequence diagram for the case where the kanji is found and the case where it is not found. It may need to be modified.

**Comment by ani-hovhannisyan** [comment]
Yes, it is. If the diagram becomes too bigger on that parts we will reconstruct the diagrams.

**Comment by ani-hovhannisyan** [comment]
Moved diagrams into docs directory, commit 9de871e
