### ISSUE TITLE
Modify the name of sequence and class diagrams

### ISSUE THREAD

**Issue by TakumiHiraide** [ani-hovhannisyan/kanji-visualization#40]

**Comment by TakumiHiraide** [comment]
[sequence diagram.pdf](https://github.com/ani-hovhannisyan/kanji-visualization/files/7956713/sequence.diagram.pdf)

**Comment by TakumiHiraide** [comment]
[Class Diagram.pdf](https://github.com/ani-hovhannisyan/kanji-visualization/files/7956733/Class.Diagram.pdf)

**Comment by ani-hovhannisyan** [comment]
As the libraries are decided, and to be more clear which part is in client side and backend side, I will update the Readme with the graphs, google document and docs folder as well. The updates will be commited in "docs" directory.

**Comment by ani-hovhannisyan** [comment]
Updated Readme, dicussed details in PBL meeting, closing.
