### ISSUE TITLE
Explore the graph visualization library

### ISSUE THREAD

**Issue by wowry** [ani-hovhannisyan/kanji-visualization#44]
- [ ] Search the graph visualization library

**Comment by wowry** [comment]
I'm trying **[react-force-graph](https://github.com/vasturiano/react-force-graph)**.

Example: [3D Text nodes visualization](https://vasturiano.github.io/react-force-graph/example/text-nodes/index-3d.html)

**Comment by ani-hovhannisyan** [comment]
The library is decided, closing. Refer to 4 week milestone for further implementation.
