### ISSUE TITLE
Github dependabot finds vulnerabilities in the dependencies

### ISSUE THREAD

**Issue by ani-hovhannisyan** [ani-hovhannisyan/kanji-visualization#51]
@wowry Dependabot finds vulnerabilities in this repo (see pics), which is visible only for repository creator (me).
Do you have any ideas? Shall we avoid it or to replace the dependencies?
-->>>
![vulnerabilities_kanjivis](https://user-images.githubusercontent.com/16926499/152492062-7efe19f9-6d21-4dc3-87d6-72e533e78b29.png)
-->>>
![githubdependabot-error](https://user-images.githubusercontent.com/16926499/152492083-dcd9a10e-9a1a-4c5c-a82e-6126d6ceb440.png)

**Comment by wowry** [comment]
@ani-hovhannisyan 
Thank you for your report.
Let me think about how to respond this for a while.

**Comment by wowry** [comment]
The dependabot warning messages can be reduced by running `yarn upgrade` periodically. This can also be automated using github actions.
However, it is difficult to get rid of all the warning messages, so we may need to ignore them to some extent.

**Comment by ani-hovhannisyan** [comment]
I looked at the dependabot alerts and updated the front end version in graph-view branch as it's related to frontend deendencies. Have to merge to main to see whether dependabot sees the updates.

**Comment by ani-hovhannisyan** [comment]
Still one postcss warning was showing, so updated that too.

**Comment by ani-hovhannisyan** [comment]
Fix is in develop branch.

**Comment by ani-hovhannisyan** [comment]
Closing, as partly is ixed and next fix will be merged with develop branch.
