### ISSUE TITLE
Add test for backend REST APIs

### ISSUE THREAD

**Issue by ani-hovhannisyan** [ani-hovhannisyan/kanji-visualization#56]
Add test which will test the get request to get kanji graph data. Follow this:
https://docs.google.com/document/d/1q9L0y9OQzgb0q9xUPpt3rnvNsbCtOJyu7gly8lK9lgk/edit#  REST API in server side section. Implementation is in main.py
Currently, I test like this in command line:
Request: `curl localhost:8000/kanji-visualize`
Response: `{"detail":[{"loc":["query","kanji"],"msg":"field required","type":"value_error.missing"}]}`

Should have same json as in graph view testing, and compare both when the response comes.

**Comment by ani-hovhannisyan** [comment]
Now, I use above curl command to test it manually, and it thrown an exception when requesting these:

```
:~/git-ani/kanji-visualization/backend$ curl localhost:8000
        {"message":"Hello from FastAPI!"}

:~/git-ani/kanji-visualization/backend$ curl localhost:8000/kanji-visualize
        {"detail":[{"loc":["query","kanji"],"msg":"field required","type":"value_error.missing"}]}


:~/git-ani/kanji-visualization/backend$ curl localhost:8000/kanji-visualize/y

       {"detail":"Not Found"}

:~/git-ani/kanji-visualization/backend$ curl localhost:8000/kanji-visualize/g
        {"detail":"Not Found"}

:~/git-ani/kanji-visualization/backend$ curl localhost:8000/kanji-visualize/山
        curl: (52) Empty reply from server

:~/git-ani/kanji-visualization/backend$ curl localhost:8000/kanji-visualize
        {"detail":[{"loc":["query","kanji"],"msg":"field required","type":"value_error.missing"}]}


:~/git-ani/kanji-visualization/backend$ curl localhost:8000/kanji-visualize/山
        curl: (52) Empty reply from server

:~/git-ani/kanji-visualization/backend$ curl localhost:8000/kanji-visualize/k
        {"detail":"Not Found"}
```
See the server log atteh same time. Why the exception is thrown? if there are many handlings, and what should be in the 山 place unicode?

```
INFO:     127.0.0.1:45070 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:45120 - "GET /kanji-visualize HTTP/1.1" 422 Unprocessable Entity
INFO:     127.0.0.1:47490 - "GET /kanji-visualize/y HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:47508 - "GET /kanji-visualize/g HTTP/1.1" 404 Not Found
WARNING:  Invalid HTTP request received.
Traceback (most recent call last):
  File "/home/ani-ho/.local/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 136, in handle_events
    event = self.conn.next_event()
  File "/home/ani-ho/.local/lib/python3.8/site-packages/h11/_connection.py", line 443, in next_event
    exc._reraise_as_remote_protocol_error()
  File "/home/ani-ho/.local/lib/python3.8/site-packages/h11/_util.py", line 76, in _reraise_as_remote_protocol_error
    raise self
  File "/home/ani-ho/.local/lib/python3.8/site-packages/h11/_connection.py", line 425, in next_event
    event = self._extract_next_receive_event()
  File "/home/ani-ho/.local/lib/python3.8/site-packages/h11/_connection.py", line 367, in _extract_next_receive_event
    event = self._reader(self._receive_buffer)
  File "/home/ani-ho/.local/lib/python3.8/site-packages/h11/_readers.py", line 72, in maybe_read_from_IDLE_client
    matches = validate(
  File "/home/ani-ho/.local/lib/python3.8/site-packages/h11/_util.py", line 88, in validate
    raise LocalProtocolError(msg)
h11._util.RemoteProtocolError: illegal request line: bytearray(b'GET /kanji-visualize/\xe5\xb1\xb1 HTTP/1.1')
```

@teruto725 san I'm not sure whom to assign, usually developer should not write his own test, so what if you guide @TakumiHiraide san and he write the test?

**Comment by teruto725** [comment]
Oh. I'm using the query param.
So the url is like below.
`http:/localhost:8000/kanji-visualize?kanji=山`

Anyway, Yes. We should do api test.
@TakumiHiraide san. Im happy you write test.

**Comment by ani-hovhannisyan** [comment]
Ah, Yes! That's totally fine.
Now, I try with param:
```
$ curl http:/localhost:8000/kanji-visualize?kanji=山
$ curl: (52) Empty reply from server
```
But no json response. Will show you tomorrow's meeting.
How do you test it? I need it to test the Graph now.

**Comment by teruto725** [comment]
The cause of Error is about terminal. The terminal can't encode Japanese character. 
I tested by python script likes below. I was worked correctly.
```
import requests
r = requests.get('http://localhost:8000/kanji-visualize?kanji=山')
print(r.text)
```

**Comment by ani-hovhannisyan** [comment]
Agree, I tested via browser url field too (usual get request) and it worked fine. Thanks!

**Comment by TakumiHiraide** [comment]
I tested "main.py" , but following error happend. What is wrong?

![スクリーンショット 2022-02-08 11 52 22](https://user-images.githubusercontent.com/84693250/152909003-98204945-c75e-4644-b9d
![スクリーンショット 2022-02-08 11 53 07](https://user-images.githubusercontent.com/84693250/152909106-ef0dee6e-0b2c-4179-87b5-d29334aef9f7.png)
9-6dc17c8e2d85.png)

**Comment by TakumiHiraide** [comment]
The code "main.py" is her
![スクリーンショット 2022-02-08 11 57 26](https://user-images.githubusercontent.com/84693250/152909535-662a0472-d6c8-4ac6-82a9-1c252e8eea71.png)
e

**Comment by teruto725** [comment]
@TakumiHiraide san.
I want to try to create test case.
You can refer this article 
https://fastapi.tiangolo.com/ja/tutorial/testing/

**Comment by teruto725** [comment]
![image](https://user-images.githubusercontent.com/45113742/152915036-7092f5c5-7aef-489f-8fc1-229f1b0a1cb2.png)

**Comment by TakumiHiraide** [comment]
This code probably works, but I'm not sure this is what I should make
![スクリーンショット 2022-02-10 12 34 06](https://user-images.githubusercontent.com/84693250/153333280-6310149a-6a54-496d-a950-ad12e2cbd991.png)
.
