### ISSUE TITLE
Create Robustness Analysis Diagram

### ISSUE THREAD

**Issue by teruto725** [ani-hovhannisyan/kanji-visualization#6]
ToDo
 
- [x]  write Robustness Analysis on google docs

**Comment by ani-hovhannisyan** [comment]
Added graphs into following google doc:
https://docs.google.com/document/d/1q9L0y9OQzgb0q9xUPpt3rnvNsbCtOJyu7gly8lK9lgk/edit?usp=sharing

**Comment by ani-hovhannisyan** [comment]
Also updated the diagram of "docs/Robustness Diagram.png", commit 3a0a20e.
