### ISSUE TITLE
Create Info  view in frontend

### ISSUE THREAD

**Issue by teruto725** [ani-hovhannisyan/kanji-visualization#60]
Create info controller view on frontend.

**Comment by ani-hovhannisyan** [comment]
Added very draft version of infoView, it has some type errors, when no kanji info is still available, will fix with next commits in feature/info-view branch. There are no styles yet.
![Screenshot from 2022-02-19 01-05-37](https://user-images.githubusercontent.com/16926499/154722749-59445a24-1666-4548-adf3-589797426064.png)

**Comment by ani-hovhannisyan** [comment]
When first empty webpage was opened I got folowing error, but the info view was working fine when closing that message. I've fixed the KanjiInfo interface to type declaration in typescript:
![Screenshot from 2022-02-19 01-12-41](https://user-images.githubusercontent.com/16926499/154839611-b5edfa85-c479-475d-b4ad-1b58249c3dea.png)
.

**Comment by ani-hovhannisyan** [comment]
Also added, some styling of header text color similar to graph nodes blue.
![Screenshot from 2022-02-20 20-11-15](https://user-images.githubusercontent.com/16926499/154839693-22c7932a-7743-4011-bf79-054a25131442.png)
