### ISSUE TITLE
Application error when kanji is not found

### ISSUE THREAD

**Issue by teruto725** [ani-hovhannisyan/kanji-visualization#71]
When the kanji is not found the error will be happend.

![image](https://user-images.githubusercontent.com/45113742/154631921-546ab7ad-6628-45fb-986a-b33ef6ee7238.png)

**Comment by ani-hovhannisyan** [comment]
I got something like that today. But can't reproduce the bug. Do you remember which kanji you've typed?
Also, I get following error when typed specific 耶 kanji, maybe this can be related to same not handled error case (I guess we forgot to check the undefined variable value).
![Screenshot from 2022-02-18 21-42-30](https://user-images.githubusercontent.com/16926499/154726977-34d4a4c3-ed5d-4df3-afb9-75dd94b2c34e.png)

**Comment by ani-hovhannisyan** [comment]
This also works for me but the fix didn't cover my posted error too, that means we had 2 different bugs, so opened new one #80.
@TakumiHiraide san could you please check whether this fix has fixed the error you've seen and reported in slack?
> [1 day ago] When I enter a kanji character that is not in Jamdict, such as "瑜" into the kanji-visualizer, the screen goes blank, is this correct?
