### ISSUE TITLE
Create slides

### ISSUE THREAD

**Issue by TakumiHiraide** [ani-hovhannisyan/kanji-visualization#76]

**Comment by teruto725** [comment]
slide link

https://docs.google.com/presentation/d/1LGvf_jRu7pPyD3L4ej6M0yXuFuOxvE6_zVERzUb3Kco/edit#slide=id.g115fbb17e4e_0_0

**Comment by teruto725** [comment]
Done Development Section and Team Management Section.

**Comment by teruto725** [comment]
All Done
